# Generated by Django 4.2.1 on 2023-05-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='eng',
        ),
        migrations.RemoveField(
            model_name='post',
            name='kis',
        ),
        migrations.RemoveField(
            model_name='post',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
