# Generated by Django 4.2.1 on 2023-05-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0002_remove_post_cre_remove_post_eng_remove_post_kis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='eng',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='kis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='maths',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='science',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
